apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - image: hiephm/hello:1.0
      name: hello
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      envFrom:
        - configMapRef:
            name: hello-config