apiVersion: v1
kind: Pod
metadata:
  name: hello-2
  labels:
    app: helloworld
    env: prod
spec:
  containers:
    - image: hiephm/hello:1.0
      name: hello
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP