apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: helloworld
    env: staging
spec:
  containers:
    - image: hiephm/hello:1.0
      name: hello
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 3